In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#   패키지 설치
#   pip install sklearn
#   pip install xgboost
#   pip install lightgbm

# 데이터 전처리
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

# 지도 학습 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import SGDRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingRegressor, HistGradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# 지도 학습 - 분류
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import VotingClassifier, BaggingClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# 비지도 학습 - 군집
from sklearn.cluster import KMeans

# 성능 조절
from sklearn.model_selection import cross_validate, StratifiedKFold, KFold
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy.stats import uniform, randint

# 평가
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import roc_auc_score

from sklearn.metrics import mean_squared_error, r2_score

from sklearn.metrics import silhouette_score

# 경고 메세지 숨김
import warnings     
warnings.filterwarnings('ignore')

# 테이블 열기

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
target = iris.target

data = StandardScaler().fit_transform(data)    # 표준화

In [3]:
# 소수점
np.set_printoptions(formatter={'float_kind':'{:.4f}'.format})

# PCA

In [4]:
pca = PCA(n_components = None)             # 주성분 개수(=축소 시킬 차원 수)
# pca = PCA(n_components = None)           # 설명된 분산 비율(0~1) 

data = pca.fit_transform( data )           # 주성분 분석

pca.explained_variance_ratio_              # 설명된 분산 비율
# np.sum(pca.explained_variance_ratio_)    # 설명된 분산 총 비율

array([0.7296, 0.2285, 0.0367, 0.0052])

In [5]:
pca.explained_variance_                   # 설명된 분산

array([2.9381, 0.9202, 0.1477, 0.0209])

In [6]:
pca.components_                          # 주성분

# pca.inverse_transform( data )            # 차원 축소 전 데이터 특성

array([[0.5211, -0.2693, 0.5804, 0.5649],
       [0.3774, 0.9233, 0.0245, 0.0669],
       [-0.7196, 0.2444, 0.1421, 0.6343],
       [-0.2613, 0.1235, 0.8014, -0.5236]])